services:
  app:
    build: .
    container_name: app
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      API_KEY: ${API_KEY}
    networks:
      - backend
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    profiles: ["local", "remote"]

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "4406:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./internal/db/schema/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - backend
    profiles: ["local"]

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - backend
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    profiles: ["local"]

volumes:
  db_data:
  pgadmin_data:

networks:
  backend:
    driver: bridge